spring:
  application:
    name: feign-consumer
ribbon:
  eureka:
    enabled: true  # 默认为true。如果设置为false，Ribbon将不会从Eureka中获得服务列表，而是使用静态配置的服务列表。静态服务列表可使用：<client>.ribbon.listOfServers来指定。参考：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#spring-cloud-ribbon-without-eureka

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000

###全局配置
hystrix:
  command:
    default:
      execution:
        isolation:
          semaphore:
            # 最大并发请求数，默认10，该参数当使用ExecutionIsolationStrategy.SEMAPHORE策略时才有效。
            maxConcurrentRequests: 10
          # 隔离策略，默认是Thread, 可选THREAD｜SEMAPHORE
          strategy: SEMAPHORE
          thread:
            # 设置熔断超时时间,，默认1000ms
            timeoutInMilliseconds: 3000

            # Fallback相关的属性,这些参数可以应用于Hystrix的THREAD和SEMAPHORE策略