# 本路径下的公共配置
spring:
  cloud:
    stream:
      #指定用kafka stream来作为默认消息中间件
      default-binder: kafka
      kafka:
        binder:
          #Kafka的服务端列表，默认localhost
          brokers: 139.9.77.156:9092
eureka:
  instance:
    # 指定该Eureka实例的主机名
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:1112/eureka/
# 暴露bus-refresh接口
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
ribbon:
  eureka:
    enabled: true  # 默认为true。如果设置为false，Ribbon将不会从Eureka中获得服务列表，而是使用静态配置的服务列表。静态服务列表可使用：<client>.ribbon.listOfServers来指定。参考：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#spring-cloud-ribbon-without-eureka