server:
  port: 7001
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JiangJiangjungle/SpirngCloud-Demo/
          search-paths: config-repo
eureka:
  instance:
    # 指定该Eureka实例的主机名
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:1112/eureka/